### ISSUE TITLE
Beagle install fails

### ISSUE THREAD

**Issue by Wytamma** [EnzoAndree/ColabBEAST#2]
The installation of beagle currently fails. I think maybe there's be a version update and the beagle version used in ColabBEAST isn't pinned?

```
sed: can't read configure.ac: No such file or directory
/bin/bash: ./autogen.sh: No such file or directory
/bin/bash: ./configure: No such file or directory
make: *** No rule to make target 'install'.  Stop.
make: *** No rule to make target 'check'.  Stop.
```

**Comment by EnzoAndree** [comment]
Hello @Wytamma! you're right! beagle currently fails.

I thought it was easy to solve but I guess I was wrong. Actually, I set the installation to beagle version 3.1.2 but now I have an error when I run beast with the test datasets. 

CUDA error: "Unknown error" from file <GPUInterfaceCUDA.cpp>, line 276.

The weird thing is that `beast -beagle_info` works without any problem

If you don't have any idea... I will have to check the beagle installation more closely to solve the problem. 

Thanks for the error report!

**Comment by Wytamma** [comment]
Yeah I ran into that same issue... tried messing with the complier and changing to the new cmake install instructions but no luck :/

**Comment by EnzoAndree** [comment]
It is Fixed!  @Wytamma!!

Could you confirm that it was fixed on your side?

**Comment by Wytamma** [comment]
Awesome! yes it works :D nice work!
